apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  description: Test Backstage catalog
  annotations:
    circleci.com/project-slug: github/narvar/hub-backend
    jira/project-key: TRK
  tags:
    - python
    - node
spec:
  type: service
  lifecycle: experimental
  owner: divyaarjnani
